Neptune's Pride:
  Game ID: any(str(), null())
  API Code: any(str(), null())
  Tick Rate: int()
  Last Tick: any(int(), null())
Players: list(include('Player'))
Webhooks: list(include('Webhook'))
---
Player:
  Username: str()
  Team: any(str(), null())
Webhook:
  Service: str()
  Url: any(str(), null())
